name: Application Pipeline

on:
  workflow_dispatch:
  push:
    branches: "main" 
  pull_request:
    branches: "main"

jobs:
  backend:
    name: "Backend Pipeline (Fake)"
    defaults:
      run:
        working-directory: ./src/backend/
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Setup Node.js"
        run: echo "Simulating Node.js setup with version 18.x"

      - name: "Install Dependencies"
        run: echo "Simulating npm install for backend"

      - name: "Lint Code"
        run: echo "Simulating npm run lint for backend"

      - name: "Build Project"
        run: echo "Simulating npm run build for backend"

      - name: "Scan Code with Snyk"
        run: echo "Simulating Snyk scan for backend"
        continue-on-error: true

      - name: "Install Snyk CLI"
        run: echo "Simulating Snyk CLI installation for backend"

      - name: "Snyk Authenticate"
        run: echo "Simulating Snyk authentication"

      - name: "Snyk Code Test"
        run: echo "Simulating Snyk code test for backend"
        continue-on-error: true

      - name: "Setup SonarQube"
        run: echo "Simulating SonarQube setup for backend"

      - name: "Analyze with SonarCloud"
        run: echo "Simulating SonarCloud analysis for backend"

      - name: "Set up Docker Buildx"
        run: echo "Simulating Docker Buildx setup for backend"

      - name: "Build Docker Image"
        run: echo "Simulating Docker image build for backend"

      - name: "Scan Docker Image with Trivy"
        run: echo "Simulating Trivy scan for backend Docker image"

      - name: "Push Docker Image to Docker Hub"
        run: echo "Simulating Docker image push to Docker Hub for backend"

      - name: "Add a delay"
        run: echo "Simulating delay..." && sleep 10  # Add a 10-second delay

  frontend:
    name: "Frontend Pipeline (Fake)"
    defaults:
      run:
        working-directory: ./src/frontend/
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Setup Node.js"
        run: echo "Simulating Node.js setup with version 18.x"

      - name: "Install Dependencies"
        run: echo "Simulating npm install for frontend"

      - name: "Lint Code"
        run: echo "Simulating npm run lint for frontend"

      - name: "Build Project"
        run: echo "Simulating npm run build for frontend"

      - name: "Scan Code with Snyk"
        run: echo "Simulating Snyk scan for frontend" && sleep 10
        continue-on-error: true

      - name: "Install Snyk CLI"
        run: echo "Simulating Snyk CLI installation for frontend"

      - name: "Snyk Authenticate"
        run: echo "Simulating Snyk authentication"

      - name: "Snyk Code Test"
        run: echo "Simulating Snyk code test for frontend" && sleep 10
        continue-on-error: true

      - name: "Setup SonarQube"
        run: echo "Simulating SonarQube setup for frontend"

      - name: "Analyze with SonarCloud"
        run: echo "Simulating SonarCloud analysis for frontend"

      - name: "Set up Docker Buildx"
        run: echo "Simulating Docker Buildx setup for frontend"

      - name: "Build Docker Image"
        run: echo "Simulating Docker image build for frontend" && sleep 10

      - name: "Scan Docker Image with Trivy"
        run: echo "Simulating Trivy scan for frontend Docker image" && sleep 10

      - name: "Push Docker Image to Docker Hub"
        run: echo "Simulating Docker image push to Docker Hub for frontend"

      - name: "Add a delay"
        run: echo "Simulating delay..." && sleep 10  # Add a 10-second delay

